### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by ghost** [goodtrailer/AdventTiC#1]
Hi, I just translated your mod AdventTiC ( version : AdventTiC-1.16.5-2021.1226.0) into Chinese.
And you can find it here   https://www.mediafire.com/folder/s7x2j942korvy/AdventTiC
Can you put it in the mod's lang file in the next update please?

**Comment by goodtrailer** [comment]
Thanks for the contribution! 👍 
Added in b1170c4c8e26c0088235379ecee2d51193f4290c.
Included in release [2022.115.0](https://github.com/goodtrailer/AdventTiC/releases/tag/2022.115.0).
